[icons]
# Change these to change the icon that shows next to each module
# Anything more than 1 character long currently breaks output
# The boolean value is telling fetchplusplus whether or not to show that module
username = [ "", true ]
hostname = [ "", true ]
distro = [ "󰻀", true ]
kernel = [ "󰌢", true ]
uptime = [ "", true ]
shell = [ "", true ]
dewm = [ "", true ]
pkgs = [ "󰏖", true ]
memory = [ "󰍛", true ]
colors = [ "", true ]

[general]
show_ascii = true # Setting this to false will disable ascii in output
ascii_distro = "default" # Choose which distro's ascii image to display

# Possible distros:
# default (shows fetch++ image)
# ubuntu
# arch
# debian
# fedora
# mint
# zorin
# popos
# manjaro
# opensuse
# slackware
# centos
# redHat
# gentoo
# endeavouros
# artix
# void
# nixos
